apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: gcr.io/bacon-chat-portfolio-pipeline/baconchatportfolio:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"