name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      # Terraform variables passed via GitHub Secrets
      TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
      TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_gcp_bucket_name: ${{ secrets.TF_VAR_GCP_BUCKET_NAME }}
      TF_VAR_vpc_name: ${{ secrets.TF_VAR_VPC_NAME }}
      TF_VAR_subnet_name: ${{ secrets.TF_VAR_SUBNET_NAME }}
      TF_VAR_cluster_name: ${{ secrets.TF_VAR_CLUSTER_NAME }}
      TF_VAR_node_pool_name: ${{ secrets.TF_VAR_NODE_POOL_NAME }}
      TF_VAR_deployment_name: ${{ secrets.TF_VAR_DEPLOYMENT_NAME }}
      TF_VAR_image_name: ${{ secrets.TF_VAR_IMAGE_NAME }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Authenticate Docker to GCR
      - name: Authenticate Docker to GCR
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

      # Build Docker image
      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/baconchatportfolio:latest -f docker/WebApp/Dockerfile .

      # Push Docker image to GCR
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/baconchatportfolio:latest

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.0'

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Terraform Apply
        run: terraform apply -auto-approve tfplan