name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      # Terraform variables passed via GitHub Secrets
      TF_VAR_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_REGION: ${{ secrets.GCP_REGION }}
      TF_VAR_GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET }}
      TF_VAR_VPC_NAME: ${{ secrets.VPC_NAME }}
      TF_VAR_SUBNET_NAME: ${{ secrets.SUBNET_NAME }}
      TF_VAR_CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      TF_VAR_NODE_POOL_NAME: ${{ secrets.NODE_POOL_NAME }}
      TF_VAR_DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
      TF_VAR_IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      # Authenticate Docker to GCR
      - name: Authenticate Docker to GCR
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | docker login -u _json_key --password-stdin https://gcr.io

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/baconchatportfolio:latest -f docker/WebApp/Dockerfile .

      # Push Docker image to GCR
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/baconchatportfolio:latest

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.0'

      # Terraform Init
      - name: Terraform Init
        run: terraform init 

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.GCP_REGION }}
          TF_VAR_image_name: "gcr.io/${{ secrets.GCP_PROJECT_ID }}/baconchatportfolio:latest"
          TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.GCP_REGION }}
          TF_VAR_image_name: "gcr.io/${{ secrets.GCP_PROJECT_ID }}/baconchatportfolio:latest"
          TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}
